DOMAIN_NAME: test_basin
EXPERIMENT_ID: run_99
HYDROLOGICAL_MODEL: SUMMA
DOMAIN_DEFINITION_METHOD: lumped
SUB_GRID_DISCRETIZATION: GRUs
FORCING_DATASET: ERA5
POUR_POINT_COORDS: 51.1722/-115.5717
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
EXPERIMENT_TIME_START: 2010-01-01 01:00
EXPERIMENT_TIME_END: 2020-12-31 23:00
CALIBRATION_PERIOD: 2010-01-01, 2015-12-31
EVALUATION_PERIOD: 2016-01-01, 2020-12-31
SPINUP_PERIOD: 2010-01-01, 2010-12-31
